### PR TITLE
Allow skipping of the collection build and installation for certain environments

### PR DESCRIPTION
**Pull request by cidrblock**
Provide a mechanism for the user to skip the collection build and installation process for a subset of the environments.

README updated
tests added

Example:

```ini
# tox-ansible.ini
[ansible]
skip_collection_build_install =
    integration
```

### CODE REVIEW

**Review by hille721 — COMMENTED** [review]
make sense for me and I already tested and it basically works.
But I see an issues for the unit tests. If you do

```
skip_collection_build_install =
    unit
```

you will result in following pre-command and command for tox:

```
commands_pre = 
commands = bash -c 'cd /path/to/repo/.tox/unit-py3.9-2.15/tmp/collections/ && python -m pytest --ansible-unit-inject-only /home/hille/gitrepos/ansible_development/community/ansible_collections/ifx/community/tests/unit'
```

which will fail as the directory `/path/to/repo/.tox/unit-py3.9-2.15/tmp/collections/` was never created

**Comment by cidrblock** [comment]
> make sense for me and I already tested and it basically works. But I see an issues for the unit tests. If you do
> 
> ```
> skip_collection_build_install =
>     unit
> ```
> 
> you will result in following pre-command and command for tox:
> 
> ```
> commands_pre = 
> commands = bash -c 'cd /path/to/repo/.tox/unit-py3.9-2.15/tmp/collections/ && python -m pytest --ansible-unit-inject-only /home/hille/gitrepos/ansible_development/community/ansible_collections/ifx/community/tests/unit'
> ```
> 
> which will fail as the directory `/path/to/repo/.tox/unit-py3.9-2.15/tmp/collections/` was never created

ah, that's a great catch. I had forgotten about the cd for unit as I was really focused on the integration. fix coming :)

**Comment by cidrblock** [comment]
Moved to draft.

Thinking about this more, in the case of molecule as the integration test runner, I think it may be better to detect and use the tox installed collection rather than build it's own.

**Comment by cidrblock** [comment]
the ansible.scm collection uses the ansible-collection-path env var set by tox-ansible rather than installing the collection via molecule. much cleaner, seperation of duties.

**Pull request closed without merging**
