### PR TITLE
Avoid full dep install prior to tox run

### PR DESCRIPTION
**Pull request by cidrblock**
For the base python interpreter, only tox and tox-ansible should be needed since the collection specific deps will be installed per environment by the plugin.

This should save some set-up time and the full dep list is not needed in the base.

### CODE REVIEW

**Comment by cidrblock** [comment]
@hille721 Mind having a look?

**Comment by cidrblock** [comment]
Gonna push this one in so it can be tested. Will report back.

**Comment by cidrblock** [comment]
Looks good for thie commit:

https://github.com/ansible-collections/ansible.scm/actions/runs/5812294815/job/15757373073?pr=227

10s savings, (17s vs 7s)

**Comment by hille721** [comment]
> @hille721 Mind having a look?

I'm not using the gh action so far as I'm in my companies own Gitlab. But in the Gitlab CI there I also just install tox-ansible.

**Pull request merged**
